name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Install playwright dependencies
        run: npx playwright install --with-deps chromium

      - name: Capture Storybook screenshots
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server ./storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"

      - name: Run Argos upload
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
        run: |
          if [ -d "./screenshots" ]; then
            npm exec -- argos upload ./screenshots
          else
            echo "No screenshots directory found, skipping Argos upload."
          fi
